name: 'Terraform'

permissions:
  id-token: write   # Autorise GitHub à demander le jeton temporaire OIDC à AWS
  contents: read    # Autorise la lecture du code

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # On utilise Bash et on se place dans le dossier terraform
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    # On ne garde QUE la région ici. Plus de clés secrètes !
    env:
      AWS_REGION: 'us-east-1'

    steps:
    # 1. On récupère le code
    - name: Checkout
      uses: actions/checkout@v4

    # 2. NOUVEAU : On s'authentifie chez AWS avec OIDC
    - name: Connexion à AWS via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::123456789012:role/TonRoleGitHubActionsOIDC # <-- À MODIFIER AVEC TON ARN
        aws-region: ${{ env.AWS_REGION }}

    # 3. On installe Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 'latest'

    # 4. Terraform initialise le projet (il utilisera les accès temporaires de l'étape 2)
    - name: Terraform Init
      run: terraform init

    # 5. Terraform planifie les changements
    - name: Terraform Plan
      run: terraform plan -input=false

    - name: "Debug: Afficher le contexte"
      run: |
        echo "Quel est l'événement ? -> ${{ github.event_name }}"
        echo "Quelle est la branche (ref) ? -> ${{ github.ref }}"

    # 6. Terraform applique les changements (uniquement sur 'main')
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false